In [1]:
import numpy as np
import pandas as pd


In [2]:
array1d=np.arange(0,10,1)
arra2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arra2d)
print(array1d)
print(type(array1d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
